schema_version = "1.0.0"
id = "cv_autotrack"
version = "1.0.2"
name = "CV Auto Track"
tagline = "Fast OpenCV auto tracking with solve refinement"
maintainer = "Naoki Korematsu"
type = "add-on"
tags = ["Tracking"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
platforms = ["windows-x64", "macos-x64", "macos-arm64", "linux-x64"]
wheels = [
    "./wheels/opencv_python_headless-4.13.0.92-cp37-abi3-win_amd64.whl",
    "./wheels/opencv_python_headless-4.13.0.92-cp37-abi3-macosx_13_0_arm64.whl",
    "./wheels/opencv_python_headless-4.13.0.92-cp37-abi3-macosx_14_0_x86_64.whl",
    "./wheels/opencv_python_headless-4.13.0.92-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl",
]
